@startuml

Parcela "*"-->"1" Usuario
RegistroHistoricoClima "*"-->"1" Parcela
RegistroHistoricoRiego "*"-->"1" Parcela
InstanciaParcela "*"-->"1" Parcela
InstanciaParcela "*"-->"1" Cultivo
InstanciaParcela "*"-->"1" EstadoInstanciaParcela
RadiacionSolar "*"-->"1" Mes
RadiacionSolar "*"-->"1" Latitud
InsolacionMaxima "*"-->"1" Mes
InsolacionMaxima "*"-->"1" Latitud

class Mes {
-id
-nombre
}

class Latitud {
-id
-latitudDecimal
}

class RadiacionSolar {
-id
-valorRadiacionSolar
}

class InsolacionMaxima {
-id
-valorInsolacionMaxima
}

class Parcela {
-id
-nombre
-hectarea
-latitud
-longitud
-activa
}

class Cultivo {
-id
-nombre
-etapaInicial
-etapaDesarrollo
-etapaMedia
-etapaFinal
-kcInicial
-kcMedio
-kcFinal
-agotamientoCritico
-activo
}

class RegistroHistoricoClima {
-id
-fecha
-zonaHoraria
-intesidadPrecipitacion
-probabilidadPrecipitacion
-puntoRocio
-presionAtmosferica
-velocidadViento
-nubosidad
-temperaturaMinima
-temperaturaMaxima
-cantidadAguaLluvia
-cantidadAguaAcumulada
-eto
-etc
}

class RegistroHistoricoRiego {
-id
-fecha
-riegoSugerido
-riegoRealizado
-precipitacionMañana
}


class InstanciaParcela {
-id
-fechaSiembra
-fechaCosecha
}

class Usuario {
-id
-nombreUsuario
-contraseña
-nombre
-apellido
-dni
-telefono
-email
-estado
-fechaAlta
-fechaBaja
-superUsuario
}

class EstadoInstanciaParcela {
-id
-nombre
-descripcion
}

@enduml
