-- DELETE
DELETE FROM CLIMATE_LOG;
ALTER TABLE CLIMATE_LOG ALTER COLUMN CLIMATE_LOG_ID RESTART WITH 1;

-- INSERTS
INSERT INTO CLIMATE_LOG (DATE, TIME_ZONE, PRECIP_INTENSITY, PRECIP_PROBABILITY, PRECIP_TYPE, DEW_POINT, PRESSURE, WIND_SPEED, CLOUD_COVER, TEMP_MIN, TEMP_MAX, FK_PARCEL)
VALUES ('2019-10-1', 'América/Argentina/Catamarca', 0.75, 0.5, 'rain', 2.0, 100.1, 10.0, 0.5, 12.0, 24.0, 1);

INSERT INTO CLIMATE_LOG (DATE, TIME_ZONE, PRECIP_INTENSITY, PRECIP_PROBABILITY, PRECIP_TYPE, DEW_POINT, PRESSURE, WIND_SPEED, CLOUD_COVER, TEMP_MIN, TEMP_MAX, FK_PARCEL)
VALUES ('2019-10-1', 'América/Argentina/Catamarca', 0.75, 0.5, 'rain', 2.0, 100.1, 10.0, 0.5, 12.0, 24.0, 2);
