-- DELETES
DELETE FROM MAXIMUM_INSOLATION;
ALTER TABLE MAXIMUM_INSOLATION ALTER COLUMN MAXIMUM_INSOLATION_ID RESTART WITH 1;

DELETE FROM SOLAR_RADIATION;
ALTER TABLE SOLAR_RADIATION ALTER COLUMN SOLAR_RADIATION_ID RESTART WITH 1;

DELETE FROM LATITUDE;
ALTER TABLE LATITUDE ALTER COLUMN LATITUDE_ID RESTART WITH 1;

DELETE FROM DAY_FIFTEEN_MONTH;
ALTER TABLE DAY_FIFTEEN_MONTH ALTER COLUMN DAY_ID RESTART WITH 1;

DELETE FROM MONTH;
ALTER TABLE MONTH ALTER COLUMN MONTH_ID RESTART WITH 1;
