-- DELETES
DELETE FROM IRRIGATION_LOG;
ALTER TABLE IRRIGATION_LOG ALTER COLUMN IRRIGATION_LOG_ID RESTART WITH 1;

-- INSERTS
INSERT INTO IRRIGATION_LOG (DATE, SUGGESTED_IRRIGATION, IRRIGATION_DONE) VALUES ('2019-10-25 00:00:00', 10.0, 5.0);
