@startuml

Parcela "*"-->"1" Usuario
Parcela "*"-->"1" TipoSuelo
RegistroHistoricoClima "*"-->"1" Parcela
RegistroHistoricoRiego "*"-->"1" Parcela
InstanciaParcela "*"-->"1" Parcela
InstanciaParcela "*"-->"1" Cultivo
InstanciaParcela "*"-->"1" EstadoInstanciaParcela

class Parcela {
-id
-nombre
-hectarea
-latitud
-longitud
-profundidad
-pedregosidad
-activa
}

class Cultivo {
-id
-etapaInicial
-etapaDesarrollo
-etapaMedia
-etapaFinal
-kcInicial
-kcMedio
-kcFinal
-agotamientoCritico
-activo
}

class TipoSuelo {
-id
-nombre
-descripcion
}

class RegistroHistoricoClima {
-id
-fecha
-zonaHoraria
-intesidadPrecipitacion
-probabilidadPrecipitacion
-tipoPrecipitacion
-puntoRocio
-presionAtmosferica
-velocidadViento
-nubosidad
-temperaturaMinima
-temperaturaMaxima
-cantidadAguaLluvia
-cantidadAguaAcumulada
-eto
-etc
}

class InstanciaParcela {
-id
-fechaSiembra
-fechaCosecha
}

class RegistroHistoricoRiego {
-id
-fecha
-riegoSugerido
-riegoRealizado
}

class Usuario {
-id
-nombreUsuario
-contraseña
-nombre
-apellido
-dni
-telefono
-email
-estado
-fechaAlta
-fechaBaja
-superUsuario
}

class EstadoInstanciaParcela {
-id
-nombre
-descripcion
}

@enduml
